// build.rs — bridge crate build settings.
//
// Two things happen here:
//
//   1. Link the clang runtime library on macOS so MLX C++ can call
//      `__builtin_available(...)` (which the compiler lowers to
//      `___isPlatformVersionAtLeast`, defined in libclang_rt.osx.a).
//      Homebrew's `rustc` doesn't pull that library in by default.
//
//   2. Whitelist the mlx-c C symbols we want re-exported from the
//      bridge cdylib. mlx-sys statically links libmlxc.a into our
//      crate, but the macOS linker hides those symbols by default;
//      `-exported_symbols_list` tells it to keep them, alongside our
//      own `mlx_rb_bridge_*` exports.

use std::process::Command;

fn main() {
    if !cfg!(target_os = "macos") {
        panic!("mlx-rb only supports Apple Silicon macOS");
    }

    link_clang_rt();
    export_mlx_symbols();
}

fn link_clang_rt() {
    let dev_dir = Command::new("xcode-select")
        .arg("-p")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "/Library/Developer/CommandLineTools".to_string());

    let toolchain = format!("{dev_dir}/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang");
    let clang_dir = if std::path::Path::new(&toolchain).exists() {
        toolchain
    } else {
        format!("{dev_dir}/usr/lib/clang")
    };

    if let Ok(entries) = std::fs::read_dir(&clang_dir) {
        let mut versions: Vec<_> = entries
            .flatten()
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        versions.sort();
        if let Some(latest) = versions.last() {
            println!("cargo:rustc-link-search=native={clang_dir}/{latest}/lib/darwin");
            println!("cargo:rustc-link-lib=static=clang_rt.osx");
        }
    }
}

fn export_mlx_symbols() {
    // exports.txt lives next to Cargo.toml; CARGO_MANIFEST_DIR points
    // at the crate root which is what we want.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let exports = format!("{manifest_dir}/exports.txt");
    println!("cargo:rerun-if-changed={exports}");

    // Find mlx-sys's generated bindings.rs to know which symbols this
    // version of mlx-c actually exposes. Some older symbols (e.g.
    // mlx_device_count) were renamed upstream; we silently drop them
    // from the exports list rather than break the build.
    let bindings_path = find_mlx_sys_bindings();
    let available: std::collections::HashSet<String> = if let Some(p) = bindings_path.as_deref() {
        let body = std::fs::read_to_string(p).unwrap_or_default();
        body.lines()
            .filter_map(|l| {
                let trim = l.trim_start();
                trim.strip_prefix("pub fn ")
                    .and_then(|rest| rest.split(['(', '<']).next())
                    .map(|s| s.trim().to_string())
            })
            .collect()
    } else {
        std::collections::HashSet::new()
    };

    let raw: Vec<String> = std::fs::read_to_string(&exports)
        .expect("read exports.txt")
        .lines()
        .filter_map(|l| l.strip_prefix('_'))
        .filter(|name| name.starts_with("mlx_") && !name.contains('*'))
        .map(|s| s.to_string())
        .collect();

    let symbols: Vec<String> = raw
        .iter()
        .filter(|name| available.is_empty() || available.contains(*name))
        .cloned()
        .collect();
    let dropped: Vec<_> = raw.iter().filter(|n| !symbols.contains(n)).collect();
    if !dropped.is_empty() {
        println!("cargo:warning=mlx_bridge: skipping {} symbol(s) not in mlx-sys: {:?}",
                 dropped.len(), dropped);
    }

    // Emit a trimmed exports list to OUT_DIR and point the linker at it.
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let exports_filtered = format!("{out_dir}/exports.list");
    let mut content = String::from("_mlx_rb_bridge_*\n");
    for s in &symbols {
        content.push('_');
        content.push_str(s);
        content.push('\n');
    }
    std::fs::write(&exports_filtered, content).expect("write filtered exports");
    println!("cargo:rustc-link-arg=-Wl,-exported_symbols_list,{exports_filtered}");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let gen_path = format!("{out_dir}/force_keep.rs");
    let mut buf = String::new();
    buf.push_str("// Auto-generated by build.rs; do not edit.\n");
    buf.push_str("//\n");
    buf.push_str("// Returns the XOR of every mlx-c function address. The value\n");
    buf.push_str("// is meaningless; the act of taking the addresses inside a\n");
    buf.push_str("// reachable function defeats the linker's dead-strip pass and\n");
    buf.push_str("// keeps the mlx-c symbols available for `exports.txt` to\n");
    buf.push_str("// whitelist.\n");
    buf.push_str("#[inline(never)]\n");
    buf.push_str("pub fn mlx_rb_bridge_force_keep() -> usize {\n");
    buf.push_str("    let mut acc: usize = 0;\n");
    for name in &symbols {
        // Skip names that mlx-sys doesn't expose (architecture-specific
        // optional types, internal helpers, etc.); cfg gate at compile.
        buf.push_str(&format!(
            "    acc ^= ::mlx_sys::{name} as *const () as usize;\n"
        ));
    }
    buf.push_str("    acc\n");
    buf.push_str("}\n");
    std::fs::write(&gen_path, buf).expect("write force_keep.rs");
}

// Locate mlx-sys's bindgen output. Cargo doesn't give us a direct env
// var for it, but the OUT_DIR of dependency build scripts lives under
// `target/<profile>/build/mlx-sys-<hash>/out/bindings.rs`. We walk up
// from our own OUT_DIR to find it.
fn find_mlx_sys_bindings() -> Option<String> {
    let our_out = std::env::var("OUT_DIR").ok()?;
    let build_root = std::path::Path::new(&our_out).ancestors().nth(2)?;
    let entries = std::fs::read_dir(build_root).ok()?;
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with("mlx-sys-") {
            let candidate = entry.path().join("out").join("bindings.rs");
            if candidate.exists() {
                return Some(candidate.to_string_lossy().to_string());
            }
        }
    }
    None
}
